name: Publish to GitHub Packages

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure Maven for GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${GITHUB_ACTOR}</username>
                      <password>${{ secrets.GITHUB_TOKEN }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml

      - name: Publish package
        run: |
          if [ "${{ github.ref_name }}" == "dev" ]; then
            echo "Push detected on 'dev' branch. Deploying with '-DEV' suffix."
            mvn clean deploy -Pdev
          elif [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.base_ref }}" == "main" ]; then
            echo "Pull request merged into 'main'. Deploying with '-RELEASE' suffix."
            mvn clean deploy -Pmain
          else
            echo "No matching conditions for deployment."
          fi